export interface SignProjectItem {
  id: string;
  title: string;
  category: "LED Signage" | "3D Letters" | "Storefronts" | "Façade Branding" | "Pylon Signs" | "Internal Branding" | "Commercial Signage";
  image: string;
  tagline: string;
  description: string;
  specifications: string[];
  materials: string[];
  location: string;
  tags: string[];
}

export const OUR_WORK_PROJECTS: SignProjectItem[] = [
  {
    id: "sign-01",
    title: "Premium Acrylic 3D LED Frontlit Signage",
    category: "3D Letters",
    image: "/assets/our-work/work-01.jpeg",
    tagline: "High-luminance laser cut acrylic letters with IP67 weatherproof LED modules",
    description: "Custom precision-cut dimensional lettering installed on high-grade aluminum composite backboard, delivering crisp night-time visibility and polished daytime appearance.",
    specifications: ["LGP LED Uniform Backlighting", "Anti-UV Acrylic Sheets", "Weatherproof Transformer"],
    materials: ["Cast Acrylic", "Samsung LED Modules", "Powder-coated Aluminium"],
    location: "Commercial Arcade",
    tags: ["3D Letters", "LED Signage", "Retail"],
  },
  {
    id: "sign-02",
    title: "Architectural Storefront Façade Cladding & Sign",
    category: "Storefronts",
    image: "/assets/our-work/work-02.jpeg",
    tagline: "Turnkey exterior cladding combined with illuminated 3D brand logo",
    description: "Full architectural elevation renovation using exterior-grade ACP panels paired with front-illuminated channel letters for unmatched brand presence.",
    specifications: ["Heavy-duty subframe", "Seamless joint grooving", "Concealed wiring"],
    materials: ["4mm PVDF ACP Cladding", "Acrylic Face", "Aluminium Return"],
    location: "High Street Retail",
    tags: ["Storefronts", "Façade Branding", "LED Signage"],
  },
  {
    id: "sign-03",
    title: "Dual-Lumen Warm Glow Retail Storefront Sign",
    category: "LED Signage",
    image: "/assets/our-work/work-03.jpeg",
    tagline: "Warm 3000K ambient glow designed for upscale boutiques and cafés",
    description: "Warm-white high CRI LED illuminated letters offering inviting ambiance and luxury brand positioning along prominent commercial corridors.",
    specifications: ["3000K Warm White LEDs", "Laser-cut contour returns", "Energy efficient 12V DC"],
    materials: ["Electro-galvanized Steel", "Translucent Acrylic", "MeanWell Power Supply"],
    location: "Fashion Street",
    tags: ["LED Signage", "Storefronts", "3D Letters"],
  },
  {
    id: "sign-04",
    title: "Stainless Steel Titanium Gold Halo-Lit 3D Letters",
    category: "3D Letters",
    image: "/assets/our-work/work-04.jpeg",
    tagline: "Titanium mirror gold finish with soft reverse halo backlighting",
    description: "Exquisite craftsmanship fabricated with laser-welded grade 304 stainless steel in mirror gold finish, projecting a delicate rear silhouette halo on architectural backdrop.",
    specifications: ["SS 304 Marine Grade", "Titanium PVD Coating", "Reverse Acrylic Standoffs"],
    materials: ["Mirror Gold Stainless Steel", "Warm LED Strips", "Clear Acrylic Diffuser"],
    location: "Jewellery & Luxury Showroom",
    tags: ["3D Letters", "Commercial Signage"],
  },
  {
    id: "sign-05",
    title: "Commercial Multi-Tier illuminated Façade Sign",
    category: "Façade Branding",
    image: "/assets/our-work/work-05.jpeg",
    tagline: "Integrated building exterior fascia with high-impact brand mark",
    description: "Comprehensive multi-level commercial sign board engineered for long-distance readability across major urban traffic junctions.",
    specifications: ["High wind-load engineered", "High lumen output", "Structural steel anchor base"],
    materials: ["Aluminium Composite Sheet", "High-grade Acrylic", "Structural MS Frame"],
    location: "Main Road Complex",
    tags: ["Façade Branding", "Commercial Signage", "LED Signage"],
  },
  {
    id: "sign-06",
    title: "Modern Minimalist Backlit Box Signage",
    category: "Commercial Signage",
    image: "/assets/our-work/work-06.jpeg",
    tagline: "Edge-to-edge frameless acrylic glow box with precision stencil typography",
    description: "Contemporary illuminated cube/lightbox sign featuring uniform front illumination with high diffusion acrylic, perfect for lifestyle establishments.",
    specifications: ["Uniform illumination grid", "Dust & moisture sealed", "Matte satin face"],
    materials: ["Opal White Cast Acrylic", "Extruded Aluminium Frame", "High-density LEDs"],
    location: "Lifestyle Studio",
    tags: ["Commercial Signage", "LED Signage"],
  },
  {
    id: "sign-07",
    title: "High-Visibility Highway Fuel / Commercial Pylon Sign",
    category: "Pylon Signs",
    image: "/assets/our-work/work-07.jpeg",
    tagline: "Heavy-duty monolithic structure designed for multi-directional highway viewing",
    description: "Double-sided illuminated vertical totem sign built with structural steel framing, wind-load resistant cladding, and day-night automatic light sensors.",
    specifications: ["Wind-load rated", "Automated twilight sensor", "Internal ladder access"],
    materials: ["Galvanized MS Truss", "PVDF ACP Panels", "High-output LED modules"],
    location: "Highway Corridor",
    tags: ["Pylon Signs", "Commercial Signage", "Façade Branding"],
  },
  {
    id: "sign-08",
    title: "Precision Laser Cut Backlit ACP Sign Board",
    category: "LED Signage",
    image: "/assets/our-work/work-08.jpeg",
    tagline: "CNC router engraved stencil with push-through acrylic lettering",
    description: "Sleek dark matte ACP panel with CNC push-through acrylic typography that illuminates exclusively through the brand name for ultra-modern contrast.",
    specifications: ["Push-through 10mm acrylic", "Zero light bleeding", "Matte black face"],
    materials: ["Matte Charcoal ACP", "10mm Cast Acrylic", "High-Efficiency LED Modules"],
    location: "Corporate Hub",
    tags: ["LED Signage", "Façade Branding", "3D Letters"],
  },
  {
    id: "sign-09",
    title: "Vibrant Color LED Flex & Channel Letter Signage",
    category: "Storefronts",
    image: "/assets/our-work/work-09.jpeg",
    tagline: "Eye-catching multi-colored dimensional letters for high footfall retail",
    description: "Dynamic vibrant retail sign board combining vivid brand pantone matching with durable front acrylic and side trim capping.",
    specifications: ["Custom pantone matched", "UV resistant acrylic", "Reinforced backing"],
    materials: ["Color Cast Acrylic", "Aluminium Trimless Edge", "IP68 Waterproof LEDs"],
    location: "Shopping District",
    tags: ["Storefronts", "LED Signage"],
  },
  {
    id: "sign-10",
    title: "Contemporary Corporate Reception Branding Sign",
    category: "Internal Branding",
    image: "/assets/our-work/work-10.jpeg",
    tagline: "Sleek indoor dimensional branding on textured wood panel backdrop",
    description: "Refined indoor entrance sign with precision laser cut floating letters and soft ambient lighting for corporate headquarters.",
    specifications: ["Concealed stud mounting", "Low-voltage warm backlight", "Seamless finish"],
    materials: ["Brushed Metal / Acrylic", "Engineered Fluted Paneling", "Warm White LED"],
    location: "Corporate Headquarters",
    tags: ["Internal Branding", "3D Letters"],
  },
  {
    id: "sign-11",
    title: "Healthcare & Clinic Directional & Main Signboard",
    category: "Commercial Signage",
    image: "/assets/our-work/work-11.jpeg",
    tagline: "Clear, crisp, hygienic white illuminated signage for medical centers",
    description: "High-contrast clean institutional signage engineered for maximum clarity, emergency visibility, and longevity in coastal environments.",
    specifications: ["6500K Day-white LED", "Anti-fungal sealed casing", "Clear directional typography"],
    materials: ["Medical Grade Acrylic", "Anti-Corrosion Aluminium", "Weatherproof PSUs"],
    location: "Healthcare Center",
    tags: ["Commercial Signage", "LED Signage"],
  },
  {
    id: "sign-12",
    title: "Bespoke Restaurant Façade & Entrance Branding",
    category: "Storefronts",
    image: "/assets/our-work/work-12.jpeg",
    tagline: "Atmospheric evening glow signboard attracting dining guests",
    description: "Custom entrance signage with integrated downlighting and backlit 3D letters tailored to culinary brand aesthetic.",
    specifications: ["Ambient downlight spotlighting", "Matte textured base", "Weatherproof sealed letters"],
    materials: ["ACP Cladding", "Acrylic Letters", "Warm Spotlight Strips"],
    location: "Dine-in Promenade",
    tags: ["Storefronts", "3D Letters", "LED Signage"],
  },
  {
    id: "sign-13",
    title: "Custom Cut Silhouette Stainless Steel Backlit Sign",
    category: "3D Letters",
    image: "/assets/our-work/work-13.jpeg",
    tagline: "Solid brushed stainless steel with intense edge silhouette halo",
    description: "Heavy-duty fabricated SS letters floating off the exterior wall with rear-firing LEDs casting a stunning aura around each character.",
    specifications: ["Solid 304 Grade Stainless Steel", "Laser welded returns", "Standoff spacer mounting"],
    materials: ["Brushed SS 304", "Optical LED Modules", "Brass Wall Standoffs"],
    location: "Financial District",
    tags: ["3D Letters", "Commercial Signage"],
  },
  {
    id: "sign-14",
    title: "High-End Retail Showroom Large Fascia Cladding",
    category: "Façade Branding",
    image: "/assets/our-work/work-14.jpeg",
    tagline: "Continuous panoramic ACP cladding with dual-colored LED 3D letters",
    description: "Expansive showroom exterior renovation featuring uninterrupted sleek composite cladding with large scale illuminated typography.",
    specifications: ["Wide-span seamless grid", "High-output LED modules", "Low power consumption"],
    materials: ["4mm Metallic Finish ACP", "High-gauge Acrylic", "Structural MS Framework"],
    location: "Commercial Arcade",
    tags: ["Façade Branding", "Storefronts", "LED Signage"],
  },
  {
    id: "sign-15",
    title: "Automotive Showroom & Service Center Entrance Sign",
    category: "Commercial Signage",
    image: "/assets/our-work/work-15.jpeg",
    tagline: "Bold brand compliance sign board with exceptional daytime clarity",
    description: "Strict brand guideline execution with exact corporate color matching, crisp edge lighting, and heavy-duty industrial framing.",
    specifications: ["Brand standard color calibration", "Dual-circuit illumination", "Anti-glare acrylic"],
    materials: ["Powder-coated Aluminium", "Cast Acrylic", "Waterproof LED Modules"],
    location: "Auto Hub Zone",
    tags: ["Commercial Signage", "3D Letters"],
  },
  {
    id: "sign-16",
    title: "Multi-Unit Commercial Shopping Complex Sign",
    category: "Façade Branding",
    image: "/assets/our-work/work-16.jpeg",
    tagline: "Harmonious tenant directories and dominant anchor brand signage",
    description: "Comprehensive exterior signage structure organizing tenant brand identities while maintaining clean architectural harmony.",
    specifications: ["Modular tenant panels", "Uniform LED backlighting", "Easy maintenance access"],
    materials: ["Architectural ACP", "Acrylic 3D Letters", "Galvanized Steel Frame"],
    location: "Commercial Shopping Complex",
    tags: ["Façade Branding", "Commercial Signage", "Pylon Signs"],
  },
  {
    id: "sign-17",
    title: "Artisan Café Neon Glow & Dimensional Letter Sign",
    category: "LED Signage",
    image: "/assets/our-work/work-17.jpeg",
    tagline: "Trendy warm neon accent combined with solid dimensional 3D lettering",
    description: "Hand-crafted flexible silicone LED neon accents paired with 3D acrylic letters to create a cozy, Instagrammable storefront.",
    specifications: ["Silicone LED Flexible Neon", "Safe low voltage 12V", "Zero flicker output"],
    materials: ["Silicone Neon Flex", "Laser Acrylic", "Dark Timber/Matte Backplate"],
    location: "Urban Café District",
    tags: ["LED Signage", "Storefronts", "Internal Branding"],
  },
  {
    id: "sign-18",
    title: "Supermarket & Hypermarket Monumental Facia Sign",
    category: "Storefronts",
    image: "/assets/our-work/work-18.jpeg",
    tagline: "Massive scale storefront lettering engineered for long-range visibility",
    description: "Giant illuminated letters with internal cross-bracing and ultra-bright daylight LED arrays built for high volume retail destinations.",
    specifications: ["Internal reinforcement ribs", "Daylight visible 8000K LEDs", "Double-sealed seams"],
    materials: ["Heavy-gauge Aluminium", "High Impact Acrylic Face", "Industrial Power Supply"],
    location: "Hypermarket Plaza",
    tags: ["Storefronts", "Façade Branding", "LED Signage"],
  },
  {
    id: "sign-19",
    title: "Boutique Fashion Studio Floating Halo-Lit Sign",
    category: "3D Letters",
    image: "/assets/our-work/work-19.jpeg",
    tagline: "Delicate typography crafted in satin black with warm ambient glow",
    description: "Understated elegance featuring thin-stroke laser cut lettering elevated off the facade with soft, glare-free indirect backlighting.",
    specifications: ["Thin-stroke precision welding", "Warm 3000K diffuse illumination", "Concealed fastener pins"],
    materials: ["Satin Black Aluminium", "Optical Grade Diffuser", "IP67 LED Strip"],
    location: "Designers Row",
    tags: ["3D Letters", "Storefronts"],
  },
  {
    id: "sign-20",
    title: "Educational Institute & Academy Campus Entrance Sign",
    category: "Commercial Signage",
    image: "/assets/our-work/work-20.jpeg",
    tagline: "Prestigious dimensional identity with solid monument arch mounting",
    description: "Stately institutional branding featuring weather-sealed cast letters mounted onto stone and composite cladding entry arches.",
    specifications: ["Weatherproof outdoor grade", "Anti-graffiti coating", "Vandal-resistant fasteners"],
    materials: ["Stainless Steel 304", "Solid Core Acrylic", "Aluminium Backing"],
    location: "Campus Main Gate",
    tags: ["Commercial Signage", "3D Letters", "Pylon Signs"],
  },
  {
    id: "sign-21",
    title: "Gold Finished Retail Showroom Fascia & Accent Bands",
    category: "Façade Branding",
    image: "/assets/our-work/work-21.jpeg",
    tagline: "Luxurious brushed gold composite cladding with matching illuminated 3D letters",
    description: "Glamorous exterior showroom treatment combining mirror gold accent trims with brightly illuminated white-faced letters.",
    specifications: ["Brushed gold PVDF finish", "High CRI front lighting", "Clean invisible silicone beads"],
    materials: ["Gold Finish ACP", "High-Gloss Acrylic", "Samsung LED Modules"],
    location: "Luxury Retail Promenade",
    tags: ["Façade Branding", "Storefronts", "3D Letters"],
  },
  {
    id: "sign-22",
    title: "Corporate Campus Multi-Directional Wayfinding Sign",
    category: "Internal Branding",
    image: "/assets/our-work/work-22.jpeg",
    tagline: "Clear navigation signage system with modular directional plates",
    description: "Freestanding directional totem with interchangeable modular slat systems for corporate parks, hospitals, and convention centres.",
    specifications: ["Modular interchangeable slats", "Reflective night text", "Heavy weighted base"],
    materials: ["Extruded Anodized Aluminium", "3M Reflective Graphics", "Tempered Safety Glass"],
    location: "Corporate Tech Park",
    tags: ["Internal Branding", "Commercial Signage", "Pylon Signs"],
  },
  {
    id: "sign-23",
    title: "Signature Architectural LED Box & 3D Logo Combination",
    category: "LED Signage",
    image: "/assets/our-work/work-23.jpeg",
    tagline: "Iconic mixed-media signage integrating glowing logos and dimensional letters",
    description: "Flagship installation blending illuminated lightbox emblem with separate floating channel letters mounted on architectural wall paneling.",
    specifications: ["Mixed media fabrication", "Dual circuit control", "Thermal management heatsink"],
    materials: ["Cast Acrylic", "Electrostatic Powder Coated SS", "High-Output LEDs"],
    location: "Flagship Experience Center",
    tags: ["LED Signage", "3D Letters", "Storefronts"],
  },
];
