export const SITE_CONFIG = {
  name: "White Edge Signages",
  legalName: "White Edge Signages Pvt. Ltd.",
  tagline: "Elevating Brands Through Exceptional Signage",
  supportingTaglines: [
    "Signs That Speak",
    "Good Signs. Great Impressions.",
    "Your Brand. Their Impression.",
    "Seen. Remembered. Trusted.",
    "Brand It. Brighten It. Own It.",
    "Crafted with Precision. Built to Last. Designed to Be Remembered.",
    "Design. Craft. Install. Inspire.",
  ],
  description:
    "White Edge Signages delivers custom LED boards, 3D letters, ACP cladding, commercial signage, glass branding, wayfinding, fabrication, installation, maintenance, and complete architectural branding solutions.",
  url: "https://whiteedgesignages.com",
  phone: "+91 80899 95313",
  phoneRaw: "+918089995313",
  whatsapp: "+91 80899 95313",
  whatsappRaw: "918089995313",
  email: "whiteedgesignages@gmail.com",
  address: "White Edge Signages, Punchiry Building, Old Military Road, Payyanakkal, Kozhikode, Kerala – 673003",
  mapsLink: "https://maps.google.com/?q=White+Edge+Signages+Kozhikode",
  workingHours: "Monday – Saturday: 9:00 AM – 6:00 PM",
  socials: {
    instagram: "https://instagram.com/whiteedgesignages",
    facebook: "https://facebook.com/whiteedgesignages",
    linkedin: "https://linkedin.com/company/whiteedgesignages",
    youtube: "https://youtube.com/@whiteedgesignages",
  },
  stats: [
    { label: "Projects Completed", value: 500, suffix: "+", description: "Across retail, commercial & healthcare" },
    { label: "Brands Served", value: 250, suffix: "+", description: "Trusted by leading regional & national brands" },
    { label: "Signage Categories", value: 17, suffix: "+", description: "End-to-end bespoke solutions" },
    { label: "Commitment to Quality", value: 100, suffix: "%", description: "Precision engineering & durable finish" },
  ],
  valueStrip: [
    {
      title: "Visible",
      subtitle: "Day and night",
      description: "High-contrast LED lighting and reflective fabrication for maximum 24/7 visibility.",
      icon: "SunMedium",
    },
    {
      title: "Memorable",
      subtitle: "Leave an impression",
      description: "Architectural 3D letterforms and bold finishes that captivate passersby.",
      icon: "Sparkles",
    },
    {
      title: "Trusted",
      subtitle: "Build credibility",
      description: "Premium materials engineered for weather resistance and long-lasting strength.",
      icon: "ShieldCheck",
    },
    {
      title: "Impactful",
      subtitle: "Attract more customers",
      description: "Strategic signage placement designed to convert foot traffic into store visits.",
      icon: "TrendingUp",
    },
    {
      title: "Timeless",
      subtitle: "Built to stand the test of time",
      description: "Sturdy structural framing and anti-fade coatings for long-term reliability.",
      icon: "Award",
    },
  ],
  services: [
    {
      id: "custom-signage",
      title: "Custom Signage Solutions",
      shortDesc: "Tailor-made signage designed according to brand identity, building structure, and environment.",
      fullDesc: "We engineer bespoke indoor and outdoor signage systems tailored precisely to your brand guidelines, structural requirements, daylight conditions, and target viewer distance.",
      category: "Architectural",
      icon: "PenTool",
      image: "/assets/img14.jpg",
    },
    {
      id: "led-sign-boards",
      title: "LED Sign Boards",
      shortDesc: "Energy-efficient illuminated signage designed for high visibility day and night.",
      fullDesc: "High-lumen, low-power consumption LED illuminated signboards engineered with weatherproof module housings for uniform illumination and long lifespan.",
      category: "Illuminated",
      icon: "Zap",
      image: "/assets/img22.jpg",
    },
    {
      id: "acp-cladding-facade",
      title: "ACP Cladding and Façade Signage",
      shortDesc: "Architectural cladding and integrated signage solutions that transform commercial exteriors.",
      fullDesc: "Aluminum Composite Panel (ACP) cladding paired with integrated 3D lettering to give commercial buildings a sleek, high-end, weather-resistant outer façade.",
      category: "Façade",
      icon: "Building2",
      image: "/assets/img28.jpg",
    },
    {
      id: "acrylic-ss-3d-letters",
      title: "Acrylic and Stainless-Steel 3D Letters",
      shortDesc: "Dimensional letters manufactured using acrylic, stainless steel, aluminium, and lighting.",
      fullDesc: "Precision CNC and laser-cut 3D dimensional lettering crafted from grade-304 stainless steel, brass, titanium-finish steel, or crystal-clear acrylic.",
      category: "Dimensional",
      icon: "Layers",
      image: "/assets/img34.jpg",
    },
    {
      id: "glow-sign-boards",
      title: "Glow Sign Boards",
      shortDesc: "High-visibility illuminated signboards for retail stores, restaurants, hospitals, and offices.",
      fullDesc: "Heavy-duty flex glow sign boards featuring vibrant translucent graphics and interior LED tube arrays for maximum roadside presence.",
      category: "Illuminated",
      icon: "Sun",
      image: "/assets/img40.jpg",
    },
    {
      id: "pylon-totem-signage",
      title: "Pylon and Totem Signage",
      shortDesc: "Tall freestanding signs for petrol bunks, shopping complexes, campuses, and highways.",
      fullDesc: "Freestanding vertical pylons engineered with structural steel framing, wind-load compliance, and dual-sided illuminated brand panels.",
      category: "Outdoor",
      icon: "Navigation2",
      image: "/assets/img22.jpg",
    },
    {
      id: "one-way-vision",
      title: "One-Way Vision Pasting",
      shortDesc: "Printed window graphics delivering outward branding while maintaining interior visibility.",
      fullDesc: "Perforated window film that presents high-impact vibrant advertising on the exterior while allowing occupants inside to see outside clearly.",
      category: "Window",
      icon: "Eye",
      image: "/assets/img46.jpg",
    },
    {
      id: "frosted-film-glass",
      title: "Frosted Film and Glass Branding",
      shortDesc: "Glass-film installations for privacy, corporate logos, conference rooms, and offices.",
      fullDesc: "Precision plotter-cut frosted privacy films with custom corporate logos, geometric patterns, and gradient dustings for glass partitions.",
      category: "Internal Branding",
      icon: "Grid",
      image: "/assets/img48.jpg",
    },
    {
      id: "commercial-vinyl-graphics",
      title: "Commercial Vinyl Graphics",
      shortDesc: "Custom vinyl graphics for walls, windows, interiors, retail stores, and promotional spaces.",
      fullDesc: "High-tack polymeric vinyl wraps printed with UV-cured inks for floor graphics, promotional window displays, and accent graphics.",
      category: "Graphics",
      icon: "Image",
      image: "/assets/img46.jpg",
    },
    {
      id: "feature-murals-interior",
      title: "Feature Murals and Internal Branding",
      shortDesc: "Custom wall murals that transform empty interiors into inspiring brand environments.",
      fullDesc: "Seamless wall coverings and large-format wall art designed to communicate corporate values, brand history, or soothing artistic ambiance.",
      category: "Internal Branding",
      icon: "Palette",
      image: "/assets/img48.jpg",
    },
    {
      id: "signage-installation",
      title: "Signage Installation",
      shortDesc: "Professional installation completed by trained technicians focusing on safety and precision.",
      fullDesc: "Certified installation crew equipped with scaffolding, boom lifts, structural anchors, and electrical safety gear for secure setup.",
      category: "Services",
      icon: "Wrench",
      image: "/assets/img14.jpg",
    },
    {
      id: "maintenance-service",
      title: "Signage Renovation & Maintenance",
      shortDesc: "Comprehensive signage renovation, structural refurbishment, LED upgrades, face cleaning, and preventive maintenance.",
      fullDesc: "Breathe new life into aging, weathered, or damaged signboards. We provide complete signage renovation, structural reinforcement, high-efficiency LED module & driver upgrades, ACP panel recoating, face panel replacement, electrical audits, and scheduled preventive maintenance.",
      category: "Services",
      icon: "ShieldAlert",
      image: "/assets/img22.jpg",
    },
    {
      id: "site-survey-consultation",
      title: "Site Survey and Consultation",
      shortDesc: "On-site evaluation covering dimensions, visibility, structural conditions, and electrical load.",
      fullDesc: "Comprehensive site audits analyzing viewing angles, wall strength, electrical hookup points, local municipal regulations, and precise laser measurements.",
      category: "Planning",
      icon: "Compass",
      image: "/assets/img34.jpg",
    },
    {
      id: "design-project-planning",
      title: "Signage Design and Project Planning",
      shortDesc: "Brand-focused design, technical drawings, material planning, costing, and strategy.",
      fullDesc: "Photorealistic 3D architectural mockups, CAD engineering drawings, material bill-of-quantities, and turn-key execution timelines.",
      category: "Planning",
      icon: "FileText",
      image: "/assets/img40.jpg",
    },
    {
      id: "wayfinding-directional",
      title: "Wayfinding and Directional Signage",
      shortDesc: "Navigation systems for hospitals, campuses, offices, malls, and residential projects.",
      fullDesc: "Intuitive directory boards, ceiling suspended directional arrows, tactile braille room signs, and floor level markers.",
      category: "Architectural",
      icon: "MapPin",
      image: "/assets/img28.jpg",
    },
    {
      id: "commercial-retail-solutions",
      title: "Commercial and Retail Signage Solutions",
      shortDesc: "Complete signage packages for shops, showrooms, restaurants, and multi-location businesses.",
      fullDesc: "Turnkey multi-asset signage packages combining exterior pylon, main entrance 3D LED letters, POS backdrop graphics, and window privacy films.",
      category: "Turnkey",
      icon: "Store",
      image: "/assets/img22.jpg",
    },
  ],
  projects: [
    {
      id: "chef-lebanon",
      title: "Chef Lebanon Restaurant",
      category: "Storefronts",
      categoryKey: "storefronts",
      location: "Kozhikode, India",
      image: "/assets/img22.jpg",
      description: "Premium illuminated storefront branding with custom warm ambient LED backlighting and architectural entrance framing.",
      tags: ["LED Signage", "Storefronts", "3D Letters"],
    },
    {
      id: "hp-petrol-bunk",
      title: "HP Petrol Fuel Station Canopy",
      category: "Pylon Signs",
      categoryKey: "pylon-signs",
      location: "Highway Corridor",
      image: "/assets/img22.jpg",
      description: "Illuminated canopy fascia branding, high-mast pylon totem, and high-visibility perimeter lighting.",
      tags: ["Pylon Signs", "Illuminated", "Commercial"],
    },
    {
      id: "damro-furniture",
      title: "DAMRO Furniture Mega Showroom",
      category: "Façade Branding",
      categoryKey: "facade-branding",
      location: "Commercial Arcade",
      image: "/assets/img22.jpg",
      description: "Large-scale storefront ACP cladding, illuminated dual-language 3D letterforms, and promotional banner framing.",
      tags: ["Façade Branding", "3D Letters", "Retail"],
    },
    {
      id: "zycho-sculpt",
      title: "ZYCHO & SCULPT Luxury Boutiques",
      category: "3D Letters",
      categoryKey: "3d-letters",
      location: "Fashion Street",
      image: "/assets/img34.jpg",
      description: "Back-lit brushed metal dimensional letters mounted on textured architectural stone grid backdrop.",
      tags: ["3D Letters", "LED Signage", "Retail"],
    },
    {
      id: "allianz-office-mural",
      title: "Allianz Corporate Workplace Mural",
      category: "Internal Branding",
      categoryKey: "internal-branding",
      location: "Tech Park Campus",
      image: "/assets/img46.jpg",
      description: "Custom high-resolution biophilic forest wall graphic mural and 3D acrylic brand emblem.",
      tags: ["Internal Branding", "Commercial Graphics"],
    },
    {
      id: "frosted-glass-partitions",
      title: "Corporate Conference Glass Branding",
      category: "Glass Films",
      categoryKey: "glass-films",
      location: "Financial Center",
      image: "/assets/img48.jpg",
      description: "Precision-cut frosted privacy film with geometric pill-shaped patterns and conference room privacy bands.",
      tags: ["Glass Films", "Internal Branding"],
    },
    {
      id: "iic-lakshya",
      title: "Indian Institute of Commerce Lakshya",
      category: "LED Signage",
      categoryKey: "led-signage",
      location: "Educational Campus",
      image: "/assets/img34.jpg",
      description: "High-contrast illuminated institutional building sign with crisp white LED module lettering.",
      tags: ["LED Signage", "Façade Branding"],
    },
    {
      id: "sns-froleo-retail",
      title: "SNS & Froleo Commercial Hub",
      category: "Commercial Graphics",
      categoryKey: "commercial-graphics",
      location: "Retail Arcade",
      image: "/assets/img14.jpg",
      description: "Multi-tenant illuminated sign fascia combining golden back-lit acrylic and circular hanging glow pods.",
      tags: ["Commercial Graphics", "LED Signage"],
    },
  ],
  industries: [
    { title: "Retail Stores", desc: "Storefront signage, illuminated 3D letters, and POS branding.", icon: "ShoppingBag", image: "/assets/img14.jpg" },
    { title: "Shopping Centres", desc: "Large façade branding, directory pylons, and tenant signboards.", icon: "Building", image: "/assets/img22.jpg" },
    { title: "Restaurants & Cafés", desc: "Ambient neon glow signs, menu boards, and outdoor entrance signage.", icon: "Utensils", image: "/assets/img34.jpg" },
    { title: "Hotels & Hospitality", desc: "Elegantly illuminated main building logos and room wayfinding.", icon: "Hotel", image: "/assets/img22.jpg" },
    { title: "Corporate Offices", desc: "Glass frosted privacy films, lobby backdrops, and wall murals.", icon: "Briefcase", image: "/assets/img48.jpg" },
    { title: "Hospitals & Healthcare", desc: "Emergency wayfinding pylons, illuminated entrance signs, and interior maps.", icon: "Activity", image: "/assets/img28.jpg" },
    { title: "Educational Institutions", desc: "Main entrance institutional signage, directional monoliths, and auditorium graphics.", icon: "GraduationCap", image: "/assets/img34.jpg" },
    { title: "Petrol Bunks", desc: "Canopy fascia branding, LED pricing totems, and safety signage.", icon: "Fuel", image: "/assets/img22.jpg" },
    { title: "Supermarkets", desc: "High-impact glow signboards, aisle banners, and exterior banners.", icon: "ShoppingCart", image: "/assets/img14.jpg" },
    { title: "Furniture Showrooms", desc: "Large-format ACP façade cladding and dual-language illuminated titles.", icon: "Armchair", image: "/assets/img22.jpg" },
    { title: "Automotive Businesses", desc: "Showroom façade branding, service center wayfinding, and pylons.", icon: "Car", image: "/assets/img28.jpg" },
    { title: "Commercial Buildings", desc: "Multi-tenant entrance directories, rooftop signs, and lobby branding.", icon: "Landmark", image: "/assets/img34.jpg" },
    { title: "Residential Developments", desc: "Gate entrance monoliths, block directional markers, and amenity signage.", icon: "Home", image: "/assets/img46.jpg" },
    { title: "Industrial Facilities", desc: "Perimeter pylon signage, safety graphic boards, and plant directories.", icon: "Factory", image: "/assets/img40.jpg" },
  ],
  whyChooseUs: [
    {
      title: "Creative Design",
      desc: "Unique, innovative, and brand-focused designs that create a memorable first impression.",
      icon: "Palette",
    },
    {
      title: "Quality Materials",
      desc: "Premium materials and reliable components selected for long-term strength, finish, and performance.",
      icon: "ShieldCheck",
    },
    {
      title: "Precision Manufacturing",
      desc: "Modern fabrication methods and skilled craftsmanship for accurate finishing and durable construction.",
      icon: "Cpu",
    },
    {
      title: "Expert Installation",
      desc: "Professional installation by experienced technicians with close attention to safety, alignment, and finishing.",
      icon: "Wrench",
    },
  ],
  additionalBenefits: [
    "End-to-end project execution",
    "Custom solutions for every brand",
    "Strong attention to detail",
    "Reliable delivery",
    "Professional site coordination",
    "Maintenance and after-sales support",
  ],
  processSteps: [
    {
      step: "01",
      title: "Consultation",
      desc: "Understand the brand, site, budget, objectives, and visibility requirements.",
    },
    {
      step: "02",
      title: "Site Survey",
      desc: "Inspect the location, take measurements, and review structural and electrical conditions.",
    },
    {
      step: "03",
      title: "Design and Planning",
      desc: "Develop creative concepts, technical layouts, material selections, and project specifications.",
    },
    {
      step: "04",
      title: "Manufacturing",
      desc: "Fabricate the signage using approved materials, precision machinery, and experienced craftsmanship.",
    },
    {
      step: "05",
      title: "Installation",
      desc: "Complete safe, professional, and accurately aligned on-site installation.",
    },
    {
      step: "06",
      title: "Support",
      desc: "Provide signage renovation, structural refurbishment, preventive maintenance, and long-term service assistance.",
    },
  ],
  testimonials: [
    {
      quote:
        "White Edge Signages transformed our retail showroom façade with stunning illuminated 3D letters and sleek ACP cladding. The quality of fabrication and nighttime visibility is outstanding!",
      author: "Rajesh Kumar",
      title: "Operations Director",
      company: "Commercial Retail Group",
      rating: 5,
    },
    {
      quote:
        "From site survey and structural planning to flawless nighttime installation, White Edge delivered on every single commitment for our fuel station network. Truly professional craftsmanship.",
      author: "Anish Nair",
      title: "Regional Manager",
      company: "Fuel Infrastructure Corp",
      rating: 5,
    },
    {
      quote:
        "The frosted glass privacy film and custom biophilic interior murals in our head office were completed with unbelievable precision. Our workspace feels completely elevated.",
      author: "Siddharth Sen",
      title: "Head of Infrastructure",
      company: "Apex Tech Solutions",
      rating: 5,
    },
  ],
  faqs: [
    {
      question: "What types of signage do you manufacture?",
      answer:
        "We manufacture custom LED boards, 3D letters, glow signs, pylon signs, façade signage, ACP cladding, wayfinding signs, vinyl graphics, glass films, murals, and other customized branding solutions.",
    },
    {
      question: "Do you handle design and installation?",
      answer:
        "Yes. We provide complete support from consultation, site survey, design, planning, and manufacturing through installation and maintenance.",
    },
    {
      question: "Can you create custom signage based on our brand guidelines?",
      answer:
        "Yes. Every project can be customized according to your logo, colors, typography, building design, visibility requirements, and budget.",
    },
    {
      question: "Do you undertake large commercial projects?",
      answer:
        "Yes. The company can deliver signage for retail spaces, offices, hospitality venues, healthcare facilities, educational institutions, petrol bunks, and commercial developments.",
    },
    {
      question: "Do you provide signage renovation and maintenance?",
      answer:
        "Yes. We provide complete signage renovation, LED driver & module replacements, face panel refurbishment, structural repairs, electrical audits, and scheduled preventive maintenance.",
    },
    {
      question: "Do you offer glass films and internal wall branding?",
      answer:
        "Yes. Services include frosted films, privacy films, corporate glass branding, commercial vinyl graphics, feature murals, and internal branding.",
    },
  ],
};
